import type { Identity } from 'spacetimedb';
// Generated by `pnpm stdb:generate` — run it after every server schema change.
import { DbConnection } from '../module_bindings';
import { DEBUG, debug } from '../debug';

const pageOrigin = typeof location === 'undefined' ? 'http://localhost:5173' : location.origin;
const URI = import.meta.env.DEV ? pageOrigin.replace(/^http/, 'ws') : (import.meta.env.VITE_STDB_URI?.trim() || pageOrigin.replace(/^http/, 'ws'));
const DB = import.meta.env.VITE_STDB_DB ?? 'doodle-arena';

export interface Connected {
  conn: DbConnection;
  identity: Identity;
}

/**
 * Connect with a per-role token so a laptop can be both /screen and /play in two tabs
 * during dev without sharing an identity. Tokens persist in localStorage → reconnecting
 * phones keep their player row + color.
 */
export function connect(role: 'screen' | 'play'): Promise<Connected> {
  const tokenKey = `doodle.token.${role}:${URI}:${DB}`;
  let saved: string | undefined;
  try { saved = localStorage.getItem(tokenKey) ?? undefined; } catch { /* private mode */ }

  return new Promise((resolve, reject) => {
    const attempt = (token: string | undefined, canRetry: boolean) => {
      let done = false;
      let connection: DbConnection | undefined;
      const timer = setTimeout(() => {
        if (done) return;
        done = true; connection?.disconnect();
        reject(new Error('Could not reach the game server. Check that the server is running, then retry.'));
      }, 10000);
      connection = DbConnection.builder()
      .withUri(URI)
      .withDatabaseName(DB)
      .withToken(token)
      .onConnect((conn, identity, token) => {
        if (done) { conn.disconnect(); return; }
        done = true; clearTimeout(timer);
        try { localStorage.setItem(tokenKey, token); } catch { /* ignore */ }
        if (DEBUG) {
          const since = Date.now();
          debug.addProvider(() => [{ level: 'ok', text: `${role} · connected ${Math.round((Date.now() - since) / 1000)}s · ${URI}/${DB} · me ${identity.toHexString().slice(0, 8)}` }]);
        }
        resolve({ conn, identity });
      })
      .onConnectError((_ctx, err) => {
        if (done) return;
        done = true; clearTimeout(timer);
        // Tokens from local SpacetimeDB cannot authenticate against maincloud.
        if (token && canRetry && /verify token|invalid token|expired token/i.test(String(err))) {
          try { localStorage.removeItem(tokenKey); } catch { /* storage blocked */ }
          attempt(undefined, false);
          return;
        }
        debug.error('connect', `${URI}: ${String(err)}`);
        reject(err);
      })
      .onDisconnect((_ctx, err) => {
        console.warn('[stdb] disconnected');
        debug.error('connection', `disconnected${err ? `: ${String(err)}` : ''} — reload to reconnect`);
        if (!done || document.getElementById('connection-lost')) return;
        const notice = document.createElement('div');
        notice.id = 'connection-lost';
        notice.className = 'connection-lost';
        notice.setAttribute('role', 'alert');
        notice.innerHTML = '<span>Disconnected from the game. Reconnect to see your room.</span><button type="button">Reconnect</button>';
        notice.querySelector('button')!.onclick = () => location.reload();
        document.body.appendChild(notice);
      })
      .build();
    };
    attempt(saved, true);
  });
}
